[default]
solc_version = "0.8.13"
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]
fuzz_runs = 256
verbosity = 3

[ci]
fuzz_runs = 1024
verbosity = 5