[default]
solc_version = "0.8.13"
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
fuzz_runs = 256
verbosity = 3
gas_reports = ["*"]
optimizer_runs = 200

[ci]
fuzz_runs = 1024
verbosity = 5
