name: Generate Merkle Root

on:
  push:
    branches:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: Generate Merkle Root
        run: npm run generate:merkle -- ./data/space
