name: Static Analysis

on:
  push:
    branches:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Static Analysis
        run: |
          pip3 install slither-analyzer \
          && pip3 install solc-select \
          && solc-select install 0.8.13 \
          && solc-select use 0.8.13 \
          && slither contracts/MerkleDistributor.sol \
          && slither contracts/Airdrop.sol
