name: Lint & Test

on:
  push:
    branches:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Lint
        run: npm run lint

      - name: Env
        run: cp .env.polygon-mumbai.example .env.local

      - name: Build
        run: make build

      - name: Test
        run: FOUNDRY_PROFILE=ci make test

      - name: Static Analysis
        run: |
          pip3 install slither-analyzer \
          && pip3 install solc-select \
          && solc-select install 0.8.13 \
          && solc-select use 0.8.13 \
          && slither contracts/MerkleDistributor.sol \
          && slither contracts/Airdrop.sol
